# SPDX-License-Identifier: MPL-2.0
# Copyright (c) 2024-2026 Elias Bachaalany
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
# Windows VS_VERSION_INFO resource helper for r2sql.
#
# Usage from a target's CMakeLists.txt:
#   xsql_add_versioninfo(<target>
#       FILETYPE          VFT_APP|VFT_DLL
#       DESCRIPTION       "<File description string>"
#       ORIGINAL_FILENAME "<file.exe|file.dll>")
#
# The .rc is generated by configure_file() from versioninfo.rc.in every CMake
# configure, so bumping R2SQL_VERSION_* in r2sql/version.hpp automatically flows
# into the produced binary's embedded version resource.
#
# Requires TOOL_VERSION_MAJOR/MINOR/PATCH to be set in the calling scope (the
# root CMakeLists parses version.hpp and sets them), and the RC language enabled.

set(_XSQL_VI_COMPANY "Elias Bachaalany")
set(_XSQL_VI_PRODUCT "r2sql")

function(xsql_add_versioninfo target)
  if(NOT WIN32)
    return()
  endif()

  cmake_parse_arguments(VI "" "FILETYPE;DESCRIPTION;ORIGINAL_FILENAME" "" ${ARGN})

  if(NOT VI_FILETYPE OR NOT VI_DESCRIPTION OR NOT VI_ORIGINAL_FILENAME)
    message(FATAL_ERROR
      "xsql_add_versioninfo(${target}): FILETYPE, DESCRIPTION, and ORIGINAL_FILENAME are required")
  endif()

  if(NOT DEFINED TOOL_VERSION_MAJOR
      OR NOT DEFINED TOOL_VERSION_MINOR
      OR NOT DEFINED TOOL_VERSION_PATCH)
    message(FATAL_ERROR
      "xsql_add_versioninfo(${target}): TOOL_VERSION_MAJOR/MINOR/PATCH must be set in scope")
  endif()

  set(VERINFO_FILETYPE          "${VI_FILETYPE}")
  set(VERINFO_DESCRIPTION       "${VI_DESCRIPTION}")
  set(VERINFO_ORIGINAL_FILENAME "${VI_ORIGINAL_FILENAME}")
  set(VERINFO_INTERNAL_NAME     "${target}")
  set(VERINFO_COMPANY           "${_XSQL_VI_COMPANY}")
  set(VERINFO_PRODUCT           "${_XSQL_VI_PRODUCT}")

  set(_rc_out "${CMAKE_CURRENT_BINARY_DIR}/${target}_versioninfo.rc")
  configure_file(
    "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/versioninfo.rc.in"
    "${_rc_out}"
    @ONLY)
  target_sources(${target} PRIVATE "${_rc_out}")
endfunction()
